// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: monitor/proto/monitor.proto

package monitorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliveryMode determines how messages are distributed to subscribers.
type DeliveryMode int32

const (
	DeliveryMode_DELIVERY_MODE_UNSPECIFIED DeliveryMode = 0
	DeliveryMode_DELIVERY_MODE_BROADCAST   DeliveryMode = 1
	DeliveryMode_DELIVERY_MODE_WORKER_POOL DeliveryMode = 2
)

// Enum value maps for DeliveryMode.
var (
	DeliveryMode_name = map[int32]string{
		0: "DELIVERY_MODE_UNSPECIFIED",
		1: "DELIVERY_MODE_BROADCAST",
		2: "DELIVERY_MODE_WORKER_POOL",
	}
	DeliveryMode_value = map[string]int32{
		"DELIVERY_MODE_UNSPECIFIED": 0,
		"DELIVERY_MODE_BROADCAST":   1,
		"DELIVERY_MODE_WORKER_POOL": 2,
	}
)

func (x DeliveryMode) Enum() *DeliveryMode {
	p := new(DeliveryMode)
	*p = x
	return p
}

func (x DeliveryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_monitor_proto_monitor_proto_enumTypes[0].Descriptor()
}

func (DeliveryMode) Type() protoreflect.EnumType {
	return &file_monitor_proto_monitor_proto_enumTypes[0]
}

func (x DeliveryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryMode.Descriptor instead.
func (DeliveryMode) EnumDescriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{0}
}

// Status represents the processing status of a monitor entry.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PENDING     Status = 1
	Status_STATUS_COMPLETED   Status = 2
	Status_STATUS_FAILED      Status = 3
	Status_STATUS_RETRYING    Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_COMPLETED",
		3: "STATUS_FAILED",
		4: "STATUS_RETRYING",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_COMPLETED":   2,
		"STATUS_FAILED":      3,
		"STATUS_RETRYING":    4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_monitor_proto_monitor_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_monitor_proto_monitor_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{1}
}

// Entry represents a single monitor record for event processing.
type Entry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	EventName      string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	BusId          string                 `protobuf:"bytes,4,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	DeliveryMode   DeliveryMode           `protobuf:"varint,5,opt,name=delivery_mode,json=deliveryMode,proto3,enum=monitor.v1.DeliveryMode" json:"delivery_mode,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status         Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=monitor.v1.Status" json:"status,omitempty"`
	Error          string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	RetryCount     int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Duration       *durationpb.Duration   `protobuf:"bytes,12,opt,name=duration,proto3" json:"duration,omitempty"`
	TraceId        string                 `protobuf:"bytes,13,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId         string                 `protobuf:"bytes,14,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Entry) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Entry) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Entry) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *Entry) GetDeliveryMode() DeliveryMode {
	if x != nil {
		return x.DeliveryMode
	}
	return DeliveryMode_DELIVERY_MODE_UNSPECIFIED
}

func (x *Entry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Entry) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Entry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Entry) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Entry) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Entry) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Entry) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Entry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Entry) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

// Filter specifies criteria for listing monitor entries.
type Filter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	EventName      string                 `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	BusId          string                 `protobuf:"bytes,4,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	DeliveryMode   *DeliveryMode          `protobuf:"varint,5,opt,name=delivery_mode,json=deliveryMode,proto3,enum=monitor.v1.DeliveryMode,oneof" json:"delivery_mode,omitempty"`
	Status         []Status               `protobuf:"varint,6,rep,packed,name=status,proto3,enum=monitor.v1.Status" json:"status,omitempty"`
	HasError       *bool                  `protobuf:"varint,7,opt,name=has_error,json=hasError,proto3,oneof" json:"has_error,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MinDuration    *durationpb.Duration   `protobuf:"bytes,10,opt,name=min_duration,json=minDuration,proto3" json:"min_duration,omitempty"`
	MinRetries     int32                  `protobuf:"varint,11,opt,name=min_retries,json=minRetries,proto3" json:"min_retries,omitempty"`
	Cursor         string                 `protobuf:"bytes,12,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit          int32                  `protobuf:"varint,13,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderDesc      bool                   `protobuf:"varint,14,opt,name=order_desc,json=orderDesc,proto3" json:"order_desc,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Filter) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Filter) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Filter) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *Filter) GetDeliveryMode() DeliveryMode {
	if x != nil && x.DeliveryMode != nil {
		return *x.DeliveryMode
	}
	return DeliveryMode_DELIVERY_MODE_UNSPECIFIED
}

func (x *Filter) GetStatus() []Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Filter) GetHasError() bool {
	if x != nil && x.HasError != nil {
		return *x.HasError
	}
	return false
}

func (x *Filter) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Filter) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Filter) GetMinDuration() *durationpb.Duration {
	if x != nil {
		return x.MinDuration
	}
	return nil
}

func (x *Filter) GetMinRetries() int32 {
	if x != nil {
		return x.MinRetries
	}
	return 0
}

func (x *Filter) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Filter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Filter) GetOrderDesc() bool {
	if x != nil {
		return x.OrderDesc
	}
	return false
}

// ListRequest is the request for List RPC.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// ListResponse is the response for List RPC.
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// GetRequest is the request for Get RPC.
type GetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// GetResponse is the response for Get RPC.
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// GetByEventIDRequest is the request for GetByEventID RPC.
type GetByEventIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByEventIDRequest) Reset() {
	*x = GetByEventIDRequest{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByEventIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByEventIDRequest) ProtoMessage() {}

func (x *GetByEventIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByEventIDRequest.ProtoReflect.Descriptor instead.
func (*GetByEventIDRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *GetByEventIDRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// GetByEventIDResponse is the response for GetByEventID RPC.
type GetByEventIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByEventIDResponse) Reset() {
	*x = GetByEventIDResponse{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByEventIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByEventIDResponse) ProtoMessage() {}

func (x *GetByEventIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByEventIDResponse.ProtoReflect.Descriptor instead.
func (*GetByEventIDResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *GetByEventIDResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// CountRequest is the request for Count RPC.
type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *CountRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// CountResponse is the response for Count RPC.
type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *CountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// DeleteOlderThanRequest is the request for DeleteOlderThan RPC.
type DeleteOlderThanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Age           *durationpb.Duration   `protobuf:"bytes,1,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOlderThanRequest) Reset() {
	*x = DeleteOlderThanRequest{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOlderThanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOlderThanRequest) ProtoMessage() {}

func (x *DeleteOlderThanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOlderThanRequest.ProtoReflect.Descriptor instead.
func (*DeleteOlderThanRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteOlderThanRequest) GetAge() *durationpb.Duration {
	if x != nil {
		return x.Age
	}
	return nil
}

// DeleteOlderThanResponse is the response for DeleteOlderThan RPC.
type DeleteOlderThanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOlderThanResponse) Reset() {
	*x = DeleteOlderThanResponse{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOlderThanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOlderThanResponse) ProtoMessage() {}

func (x *DeleteOlderThanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOlderThanResponse.ProtoReflect.Descriptor instead.
func (*DeleteOlderThanResponse) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteOlderThanResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

// StreamRequest is the request for Stream RPC.
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_monitor_proto_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_proto_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_monitor_proto_monitor_proto_rawDescGZIP(), []int{12}
}

func (x *StreamRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_monitor_proto_monitor_proto protoreflect.FileDescriptor

const file_monitor_proto_monitor_proto_rawDesc = "" +
	"\n" +
	"\x1bmonitor/proto/monitor.proto\x12\n" +
	"monitor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x82\x05\n" +
	"\x05Entry\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12\x15\n" +
	"\x06bus_id\x18\x04 \x01(\tR\x05busId\x12=\n" +
	"\rdelivery_mode\x18\x05 \x01(\x0e2\x18.monitor.v1.DeliveryModeR\fdeliveryMode\x12;\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1f.monitor.v1.Entry.MetadataEntryR\bmetadata\x12*\n" +
	"\x06status\x18\a \x01(\x0e2\x12.monitor.v1.StatusR\x06status\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x129\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x125\n" +
	"\bduration\x18\f \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x19\n" +
	"\btrace_id\x18\r \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x0e \x01(\tR\x06spanId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x04\n" +
	"\x06Filter\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x03 \x01(\tR\teventName\x12\x15\n" +
	"\x06bus_id\x18\x04 \x01(\tR\x05busId\x12B\n" +
	"\rdelivery_mode\x18\x05 \x01(\x0e2\x18.monitor.v1.DeliveryModeH\x00R\fdeliveryMode\x88\x01\x01\x12*\n" +
	"\x06status\x18\x06 \x03(\x0e2\x12.monitor.v1.StatusR\x06status\x12 \n" +
	"\thas_error\x18\a \x01(\bH\x01R\bhasError\x88\x01\x01\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12<\n" +
	"\fmin_duration\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\vminDuration\x12\x1f\n" +
	"\vmin_retries\x18\v \x01(\x05R\n" +
	"minRetries\x12\x16\n" +
	"\x06cursor\x18\f \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\r \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"order_desc\x18\x0e \x01(\bR\torderDescB\x10\n" +
	"\x0e_delivery_modeB\f\n" +
	"\n" +
	"_has_error\"9\n" +
	"\vListRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.monitor.v1.FilterR\x06filter\"w\n" +
	"\fListResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.monitor.v1.EntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"P\n" +
	"\n" +
	"GetRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\"6\n" +
	"\vGetResponse\x12'\n" +
	"\x05entry\x18\x01 \x01(\v2\x11.monitor.v1.EntryR\x05entry\"0\n" +
	"\x13GetByEventIDRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"C\n" +
	"\x14GetByEventIDResponse\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.monitor.v1.EntryR\aentries\":\n" +
	"\fCountRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.monitor.v1.FilterR\x06filter\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"E\n" +
	"\x16DeleteOlderThanRequest\x12+\n" +
	"\x03age\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x03age\"3\n" +
	"\x17DeleteOlderThanResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted\";\n" +
	"\rStreamRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.monitor.v1.FilterR\x06filter*i\n" +
	"\fDeliveryMode\x12\x1d\n" +
	"\x19DELIVERY_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_MODE_BROADCAST\x10\x01\x12\x1d\n" +
	"\x19DELIVERY_MODE_WORKER_POOL\x10\x02*r\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x03\x12\x13\n" +
	"\x0fSTATUS_RETRYING\x10\x042\xaa\x03\n" +
	"\x0eMonitorService\x129\n" +
	"\x04List\x12\x17.monitor.v1.ListRequest\x1a\x18.monitor.v1.ListResponse\x126\n" +
	"\x03Get\x12\x16.monitor.v1.GetRequest\x1a\x17.monitor.v1.GetResponse\x12Q\n" +
	"\fGetByEventID\x12\x1f.monitor.v1.GetByEventIDRequest\x1a .monitor.v1.GetByEventIDResponse\x12<\n" +
	"\x05Count\x12\x18.monitor.v1.CountRequest\x1a\x19.monitor.v1.CountResponse\x12Z\n" +
	"\x0fDeleteOlderThan\x12\".monitor.v1.DeleteOlderThanRequest\x1a#.monitor.v1.DeleteOlderThanResponse\x128\n" +
	"\x06Stream\x12\x19.monitor.v1.StreamRequest\x1a\x11.monitor.v1.Entry0\x01B6Z4github.com/rbaliyan/event/v3/monitor/proto;monitorpbb\x06proto3"

var (
	file_monitor_proto_monitor_proto_rawDescOnce sync.Once
	file_monitor_proto_monitor_proto_rawDescData []byte
)

func file_monitor_proto_monitor_proto_rawDescGZIP() []byte {
	file_monitor_proto_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_proto_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_proto_monitor_proto_rawDesc), len(file_monitor_proto_monitor_proto_rawDesc)))
	})
	return file_monitor_proto_monitor_proto_rawDescData
}

var file_monitor_proto_monitor_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_monitor_proto_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_monitor_proto_monitor_proto_goTypes = []any{
	(DeliveryMode)(0),               // 0: monitor.v1.DeliveryMode
	(Status)(0),                     // 1: monitor.v1.Status
	(*Entry)(nil),                   // 2: monitor.v1.Entry
	(*Filter)(nil),                  // 3: monitor.v1.Filter
	(*ListRequest)(nil),             // 4: monitor.v1.ListRequest
	(*ListResponse)(nil),            // 5: monitor.v1.ListResponse
	(*GetRequest)(nil),              // 6: monitor.v1.GetRequest
	(*GetResponse)(nil),             // 7: monitor.v1.GetResponse
	(*GetByEventIDRequest)(nil),     // 8: monitor.v1.GetByEventIDRequest
	(*GetByEventIDResponse)(nil),    // 9: monitor.v1.GetByEventIDResponse
	(*CountRequest)(nil),            // 10: monitor.v1.CountRequest
	(*CountResponse)(nil),           // 11: monitor.v1.CountResponse
	(*DeleteOlderThanRequest)(nil),  // 12: monitor.v1.DeleteOlderThanRequest
	(*DeleteOlderThanResponse)(nil), // 13: monitor.v1.DeleteOlderThanResponse
	(*StreamRequest)(nil),           // 14: monitor.v1.StreamRequest
	nil,                             // 15: monitor.v1.Entry.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 16: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),     // 17: google.protobuf.Duration
}
var file_monitor_proto_monitor_proto_depIdxs = []int32{
	0,  // 0: monitor.v1.Entry.delivery_mode:type_name -> monitor.v1.DeliveryMode
	15, // 1: monitor.v1.Entry.metadata:type_name -> monitor.v1.Entry.MetadataEntry
	1,  // 2: monitor.v1.Entry.status:type_name -> monitor.v1.Status
	16, // 3: monitor.v1.Entry.started_at:type_name -> google.protobuf.Timestamp
	16, // 4: monitor.v1.Entry.completed_at:type_name -> google.protobuf.Timestamp
	17, // 5: monitor.v1.Entry.duration:type_name -> google.protobuf.Duration
	0,  // 6: monitor.v1.Filter.delivery_mode:type_name -> monitor.v1.DeliveryMode
	1,  // 7: monitor.v1.Filter.status:type_name -> monitor.v1.Status
	16, // 8: monitor.v1.Filter.start_time:type_name -> google.protobuf.Timestamp
	16, // 9: monitor.v1.Filter.end_time:type_name -> google.protobuf.Timestamp
	17, // 10: monitor.v1.Filter.min_duration:type_name -> google.protobuf.Duration
	3,  // 11: monitor.v1.ListRequest.filter:type_name -> monitor.v1.Filter
	2,  // 12: monitor.v1.ListResponse.entries:type_name -> monitor.v1.Entry
	2,  // 13: monitor.v1.GetResponse.entry:type_name -> monitor.v1.Entry
	2,  // 14: monitor.v1.GetByEventIDResponse.entries:type_name -> monitor.v1.Entry
	3,  // 15: monitor.v1.CountRequest.filter:type_name -> monitor.v1.Filter
	17, // 16: monitor.v1.DeleteOlderThanRequest.age:type_name -> google.protobuf.Duration
	3,  // 17: monitor.v1.StreamRequest.filter:type_name -> monitor.v1.Filter
	4,  // 18: monitor.v1.MonitorService.List:input_type -> monitor.v1.ListRequest
	6,  // 19: monitor.v1.MonitorService.Get:input_type -> monitor.v1.GetRequest
	8,  // 20: monitor.v1.MonitorService.GetByEventID:input_type -> monitor.v1.GetByEventIDRequest
	10, // 21: monitor.v1.MonitorService.Count:input_type -> monitor.v1.CountRequest
	12, // 22: monitor.v1.MonitorService.DeleteOlderThan:input_type -> monitor.v1.DeleteOlderThanRequest
	14, // 23: monitor.v1.MonitorService.Stream:input_type -> monitor.v1.StreamRequest
	5,  // 24: monitor.v1.MonitorService.List:output_type -> monitor.v1.ListResponse
	7,  // 25: monitor.v1.MonitorService.Get:output_type -> monitor.v1.GetResponse
	9,  // 26: monitor.v1.MonitorService.GetByEventID:output_type -> monitor.v1.GetByEventIDResponse
	11, // 27: monitor.v1.MonitorService.Count:output_type -> monitor.v1.CountResponse
	13, // 28: monitor.v1.MonitorService.DeleteOlderThan:output_type -> monitor.v1.DeleteOlderThanResponse
	2,  // 29: monitor.v1.MonitorService.Stream:output_type -> monitor.v1.Entry
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_monitor_proto_monitor_proto_init() }
func file_monitor_proto_monitor_proto_init() {
	if File_monitor_proto_monitor_proto != nil {
		return
	}
	file_monitor_proto_monitor_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_proto_monitor_proto_rawDesc), len(file_monitor_proto_monitor_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_proto_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_proto_monitor_proto_depIdxs,
		EnumInfos:         file_monitor_proto_monitor_proto_enumTypes,
		MessageInfos:      file_monitor_proto_monitor_proto_msgTypes,
	}.Build()
	File_monitor_proto_monitor_proto = out.File
	file_monitor_proto_monitor_proto_goTypes = nil
	file_monitor_proto_monitor_proto_depIdxs = nil
}
