// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: monitor/proto/monitor.proto

package monitorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitorService_List_FullMethodName            = "/monitor.v1.MonitorService/List"
	MonitorService_Get_FullMethodName             = "/monitor.v1.MonitorService/Get"
	MonitorService_GetByEventID_FullMethodName    = "/monitor.v1.MonitorService/GetByEventID"
	MonitorService_Count_FullMethodName           = "/monitor.v1.MonitorService/Count"
	MonitorService_DeleteOlderThan_FullMethodName = "/monitor.v1.MonitorService/DeleteOlderThan"
	MonitorService_Stream_FullMethodName          = "/monitor.v1.MonitorService/Stream"
)

// MonitorServiceClient is the client API for MonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MonitorService provides event monitoring and observability.
type MonitorServiceClient interface {
	// List returns entries matching the filter with cursor-based pagination.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Get retrieves a single entry by event ID and subscription ID.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// GetByEventID returns all entries for an event ID.
	GetByEventID(ctx context.Context, in *GetByEventIDRequest, opts ...grpc.CallOption) (*GetByEventIDResponse, error)
	// Count returns the number of entries matching the filter.
	Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// DeleteOlderThan removes entries older than the specified age.
	DeleteOlderThan(ctx context.Context, in *DeleteOlderThanRequest, opts ...grpc.CallOption) (*DeleteOlderThanResponse, error)
	// Stream returns a real-time stream of entries matching the filter.
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entry], error)
}

type monitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorServiceClient(cc grpc.ClientConnInterface) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, MonitorService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, MonitorService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetByEventID(ctx context.Context, in *GetByEventIDRequest, opts ...grpc.CallOption) (*GetByEventIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByEventIDResponse)
	err := c.cc.Invoke(ctx, MonitorService_GetByEventID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, MonitorService_Count_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) DeleteOlderThan(ctx context.Context, in *DeleteOlderThanRequest, opts ...grpc.CallOption) (*DeleteOlderThanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOlderThanResponse)
	err := c.cc.Invoke(ctx, MonitorService_DeleteOlderThan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitorService_ServiceDesc.Streams[0], MonitorService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Entry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_StreamClient = grpc.ServerStreamingClient[Entry]

// MonitorServiceServer is the server API for MonitorService service.
// All implementations must embed UnimplementedMonitorServiceServer
// for forward compatibility.
//
// MonitorService provides event monitoring and observability.
type MonitorServiceServer interface {
	// List returns entries matching the filter with cursor-based pagination.
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Get retrieves a single entry by event ID and subscription ID.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// GetByEventID returns all entries for an event ID.
	GetByEventID(context.Context, *GetByEventIDRequest) (*GetByEventIDResponse, error)
	// Count returns the number of entries matching the filter.
	Count(context.Context, *CountRequest) (*CountResponse, error)
	// DeleteOlderThan removes entries older than the specified age.
	DeleteOlderThan(context.Context, *DeleteOlderThanRequest) (*DeleteOlderThanResponse, error)
	// Stream returns a real-time stream of entries matching the filter.
	Stream(*StreamRequest, grpc.ServerStreamingServer[Entry]) error
	mustEmbedUnimplementedMonitorServiceServer()
}

// UnimplementedMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitorServiceServer struct{}

func (UnimplementedMonitorServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedMonitorServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMonitorServiceServer) GetByEventID(context.Context, *GetByEventIDRequest) (*GetByEventIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByEventID not implemented")
}
func (UnimplementedMonitorServiceServer) Count(context.Context, *CountRequest) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedMonitorServiceServer) DeleteOlderThan(context.Context, *DeleteOlderThanRequest) (*DeleteOlderThanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOlderThan not implemented")
}
func (UnimplementedMonitorServiceServer) Stream(*StreamRequest, grpc.ServerStreamingServer[Entry]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedMonitorServiceServer) mustEmbedUnimplementedMonitorServiceServer() {}
func (UnimplementedMonitorServiceServer) testEmbeddedByValue()                        {}

// UnsafeMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitorServiceServer will
// result in compilation errors.
type UnsafeMonitorServiceServer interface {
	mustEmbedUnimplementedMonitorServiceServer()
}

func RegisterMonitorServiceServer(s grpc.ServiceRegistrar, srv MonitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitorService_ServiceDesc, srv)
}

func _MonitorService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetByEventID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByEventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetByEventID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_GetByEventID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetByEventID(ctx, req.(*GetByEventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).Count(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_DeleteOlderThan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOlderThanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).DeleteOlderThan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitorService_DeleteOlderThan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).DeleteOlderThan(ctx, req.(*DeleteOlderThanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitorServiceServer).Stream(m, &grpc.GenericServerStream[StreamRequest, Entry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitorService_StreamServer = grpc.ServerStreamingServer[Entry]

// MonitorService_ServiceDesc is the grpc.ServiceDesc for MonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.v1.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _MonitorService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MonitorService_Get_Handler,
		},
		{
			MethodName: "GetByEventID",
			Handler:    _MonitorService_GetByEventID_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _MonitorService_Count_Handler,
		},
		{
			MethodName: "DeleteOlderThan",
			Handler:    _MonitorService_DeleteOlderThan_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _MonitorService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monitor/proto/monitor.proto",
}
