// Package ackonly provides a transport implementation for scenarios where
// publishing happens externally (e.g., database triggers, change streams).
//
// This transport is designed for use cases where:
//   - Events are generated by external systems (database writes, file changes, etc.)
//   - Only the "receive" side needs implementation
//   - Acknowledgment semantics are still desired (ack/nack)
//
// Example use cases:
//   - MongoDB change streams: writes to collection trigger events
//   - PostgreSQL triggers: database triggers publish events
//   - File system watchers: file changes trigger events
//
// Usage:
//
//	// Create transport with optional ack backend
//	t := ackonly.New(
//	    ackonly.WithAckBackend(mongoAckStore),
//	    ackonly.WithLogger(logger),
//	)
//
//	// Register events
//	t.RegisterEvent(ctx, "orders")
//
//	// Subscribe to events
//	sub, _ := t.Subscribe(ctx, "orders")
//
//	// In your change stream handler:
//	for change := range changeStream {
//	    msg := transport.NewMessage(...)
//	    t.Deliver(ctx, "orders", msg)
//	}
package ackonly

import (
	"context"
	"errors"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"

	"github.com/rbaliyan/event/v3/transport"
	"github.com/rbaliyan/event/v3/transport/base"
)

// ErrPublishNotSupported is returned when Publish is called on an ack-only transport.
var ErrPublishNotSupported = errors.New("ack-only transport does not support Publish; use Deliver instead")

// AckBackend handles acknowledgment tracking for messages.
// Implement this interface to track which messages have been processed.
type AckBackend interface {
	// Store records a message as pending (not yet acknowledged).
	Store(ctx context.Context, eventName, msgID string) error

	// Ack marks a message as acknowledged (successfully processed).
	Ack(ctx context.Context, eventName, msgID string) error

	// Pending returns IDs of messages that haven't been acknowledged.
	// Limit controls maximum number of IDs to return (0 = no limit).
	Pending(ctx context.Context, eventName string, limit int) ([]string, error)
}

// Transport implements transport.Transport for external event sources.
// It does not support Publish - events are delivered via the Deliver method.
type Transport struct {
	status     int32
	events     sync.Map // map[string]*event
	ackBackend AckBackend
	logger     *slog.Logger
	onError    func(error)
	bufferSize int
}

// event tracks event-specific state
type event struct {
	name        string
	subscribers sync.Map // map[string]*subscription
	subCount    int64
}

// subscription implements transport.Subscription
type subscription struct {
	*base.Subscription
	eventName  string
	ackBackend AckBackend
}

// Option configures the ack-only transport
type Option func(*Transport)

// WithAckBackend sets the acknowledgment backend for tracking message processing.
func WithAckBackend(backend AckBackend) Option {
	return func(t *Transport) {
		t.ackBackend = backend
	}
}

// WithLogger sets the logger for the transport.
func WithLogger(logger *slog.Logger) Option {
	return func(t *Transport) {
		if logger != nil {
			t.logger = logger
		}
	}
}

// WithErrorHandler sets the error callback.
func WithErrorHandler(fn func(error)) Option {
	return func(t *Transport) {
		if fn != nil {
			t.onError = fn
		}
	}
}

// WithBufferSize sets the default buffer size for subscriptions.
func WithBufferSize(size int) Option {
	return func(t *Transport) {
		if size > 0 {
			t.bufferSize = size
		}
	}
}

// New creates a new ack-only transport.
func New(opts ...Option) *Transport {
	t := &Transport{
		status:     1,
		logger:     transport.Logger("transport>ack-only"),
		onError:    func(error) {},
		bufferSize: 100,
	}

	for _, opt := range opts {
		opt(t)
	}

	return t
}

func (t *Transport) isOpen() bool {
	return atomic.LoadInt32(&t.status) == 1
}

// RegisterEvent creates resources for an event.
func (t *Transport) RegisterEvent(ctx context.Context, name string) error {
	if !t.isOpen() {
		return transport.ErrTransportClosed
	}

	ev := &event{name: name}

	if _, loaded := t.events.LoadOrStore(name, ev); loaded {
		return transport.ErrEventAlreadyExists
	}

	t.logger.Debug("registered event", "event", name)
	return nil
}

// UnregisterEvent cleans up event resources.
func (t *Transport) UnregisterEvent(ctx context.Context, name string) error {
	if !t.isOpen() {
		return transport.ErrTransportClosed
	}

	val, ok := t.events.LoadAndDelete(name)
	if !ok {
		return transport.ErrEventNotRegistered
	}

	// Close all subscriptions
	ev := val.(*event)
	ev.subscribers.Range(func(key, value any) bool {
		sub := value.(*subscription)
		sub.Close(ctx)
		return true
	})

	t.logger.Debug("unregistered event", "event", name)
	return nil
}

// Publish is not supported by ack-only transport.
// Use Deliver to send messages from external sources.
func (t *Transport) Publish(ctx context.Context, name string, msg transport.Message) error {
	return ErrPublishNotSupported
}

// Deliver sends a message to all subscribers of an event.
// This is called by external systems (change streams, triggers, etc.) when events occur.
//
// The message will be wrapped with an ack function if an AckBackend is configured.
// Subscribers can call msg.Ack(nil) on success or msg.Ack(err) on failure.
func (t *Transport) Deliver(ctx context.Context, eventName string, msg transport.Message) error {
	if !t.isOpen() {
		return transport.ErrTransportClosed
	}

	val, ok := t.events.Load(eventName)
	if !ok {
		return transport.ErrEventNotRegistered
	}

	ev := val.(*event)

	// Record message as pending (if backend configured)
	if t.ackBackend != nil {
		if err := t.ackBackend.Store(ctx, eventName, msg.ID()); err != nil {
			t.onError(err)
			t.logger.Error("failed to store pending message", "event", eventName, "msg_id", msg.ID(), "error", err)
			// Continue anyway - don't block delivery
		}
	}

	// Wrap message with ack function
	wrappedMsg := transport.NewMessageWithAck(
		msg.ID(),
		msg.Source(),
		msg.Payload(),
		msg.Metadata(),
		msg.RetryCount(),
		func(err error) error {
			if err == nil && t.ackBackend != nil {
				return t.ackBackend.Ack(ctx, eventName, msg.ID())
			}
			return nil
		},
	)

	// Send to all subscribers
	var delivered int
	ev.subscribers.Range(func(key, value any) bool {
		sub := value.(*subscription)
		if sub.IsClosed() {
			return true
		}

		// Non-blocking send with fallback to blocking
		select {
		case sub.Ch() <- wrappedMsg:
			delivered++
		default:
			// Channel full - try blocking send
			select {
			case sub.Ch() <- wrappedMsg:
				delivered++
			case <-sub.ClosedCh():
				// Subscriber closed
			}
		}
		return true
	})

	if delivered == 0 && atomic.LoadInt64(&ev.subCount) > 0 {
		t.logger.Debug("message not delivered to any subscriber", "event", eventName, "msg_id", msg.ID())
	}

	return nil
}

// Subscribe creates a subscription to receive messages for an event.
func (t *Transport) Subscribe(ctx context.Context, name string, opts ...transport.SubscribeOption) (transport.Subscription, error) {
	if !t.isOpen() {
		return nil, transport.ErrTransportClosed
	}

	subOpts := transport.ApplySubscribeOptions(opts...)

	val, ok := t.events.Load(name)
	if !ok {
		return nil, transport.ErrEventNotRegistered
	}

	ev := val.(*event)

	bufSize := t.bufferSize
	if subOpts.BufferSize > 0 {
		bufSize = subOpts.BufferSize
	}

	subID := transport.NewID()
	sub := &subscription{
		Subscription: base.NewSubscription(subID, bufSize, 0),
		eventName:    name,
		ackBackend:   t.ackBackend,
	}

	ev.subscribers.Store(sub.ID(), sub)
	atomic.AddInt64(&ev.subCount, 1)

	t.logger.Debug("added subscriber", "event", name, "subscriber", sub.ID())
	return sub, nil
}

// Close shuts down the transport.
func (t *Transport) Close(ctx context.Context) error {
	if !atomic.CompareAndSwapInt32(&t.status, 1, 0) {
		return nil
	}

	// Close all subscriptions
	t.events.Range(func(key, value any) bool {
		ev := value.(*event)
		ev.subscribers.Range(func(k, v any) bool {
			sub := v.(*subscription)
			sub.Close(ctx)
			return true
		})
		return true
	})

	t.logger.Debug("transport closed")
	return nil
}

// Health performs a health check on the transport.
func (t *Transport) Health(ctx context.Context) *transport.HealthCheckResult {
	start := time.Now()

	result := &transport.HealthCheckResult{
		CheckedAt: start,
		Details:   make(map[string]any),
	}

	if !t.isOpen() {
		result.Status = transport.HealthStatusUnhealthy
		result.Message = "transport is closed"
		result.Latency = time.Since(start)
		return result
	}

	// Count events and subscribers
	var eventCount int
	var totalSubs int64
	t.events.Range(func(key, value any) bool {
		eventCount++
		ev := value.(*event)
		totalSubs += atomic.LoadInt64(&ev.subCount)
		return true
	})

	result.Status = transport.HealthStatusHealthy
	result.Message = "ack-only transport is healthy"
	result.Latency = time.Since(start)
	result.Details["type"] = "ack-only"
	result.Details["events"] = eventCount
	result.Details["subscribers"] = totalSubs
	result.Details["has_ack_backend"] = t.ackBackend != nil

	return result
}

// subscription methods

func (s *subscription) Close(ctx context.Context) error {
	return s.Subscription.Close(func() error {
		return nil
	})
}

// Compile-time checks
var (
	_ transport.Transport     = (*Transport)(nil)
	_ transport.HealthChecker = (*Transport)(nil)
	_ transport.Subscription  = (*subscription)(nil)
)
