#!/bin/bash -eu
compile_native_go_fuzzer github.com/rbaliyan/event/v3/payload FuzzJSONCodecDecode fuzz_json_codec_decode
compile_native_go_fuzzer github.com/rbaliyan/event/v3/payload FuzzMsgPackCodecDecode fuzz_msgpack_codec_decode
compile_native_go_fuzzer github.com/rbaliyan/event/v3/transport/codec FuzzJSONTransportCodecDecode fuzz_json_transport_codec_decode
compile_native_go_fuzzer github.com/rbaliyan/event/v3/transport/codec FuzzMsgPackTransportCodecDecode fuzz_msgpack_transport_codec_decode
compile_native_go_fuzzer github.com/rbaliyan/event/v3/validation FuzzNewJSONSchemaValidator fuzz_new_json_schema_validator
compile_native_go_fuzzer github.com/rbaliyan/event/v3/validation FuzzJSONSchemaValidate fuzz_json_schema_validate
compile_native_go_fuzzer github.com/rbaliyan/event/v3/schema FuzzDecodeEnvelope fuzz_decode_envelope
compile_native_go_fuzzer github.com/rbaliyan/event/v3/schema FuzzJSONSchemaValidate fuzz_json_schema_validate_schema
compile_native_go_fuzzer github.com/rbaliyan/event/v3/schema FuzzFieldMapperUpcast fuzz_field_mapper_upcast
