// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: transport/message/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProtoMessage is the wire format for event messages using Protocol Buffers.
// Payload is stored as pre-encoded bytes.
type ProtoMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique message identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Source of the message (usually bus ID)
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Optional metadata key-value pairs
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Number of times this message has been retried
	RetryCount int32 `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	// Pre-encoded payload bytes
	Payload       []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMessage) Reset() {
	*x = ProtoMessage{}
	mi := &file_transport_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMessage) ProtoMessage() {}

func (x *ProtoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_transport_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMessage.ProtoReflect.Descriptor instead.
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return file_transport_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProtoMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProtoMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProtoMessage) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ProtoMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_transport_message_message_proto protoreflect.FileDescriptor

const file_transport_message_message_proto_rawDesc = "" +
	"\n" +
	"\x1ftransport/message/message.proto\x12\amessage\"\xef\x01\n" +
	"\fProtoMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12?\n" +
	"\bmetadata\x18\x03 \x03(\v2#.message.ProtoMessage.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B0Z.github.com/rbaliyan/event/v3/transport/messageb\x06proto3"

var (
	file_transport_message_message_proto_rawDescOnce sync.Once
	file_transport_message_message_proto_rawDescData []byte
)

func file_transport_message_message_proto_rawDescGZIP() []byte {
	file_transport_message_message_proto_rawDescOnce.Do(func() {
		file_transport_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_message_message_proto_rawDesc), len(file_transport_message_message_proto_rawDesc)))
	})
	return file_transport_message_message_proto_rawDescData
}

var file_transport_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_message_message_proto_goTypes = []any{
	(*ProtoMessage)(nil), // 0: message.ProtoMessage
	nil,                  // 1: message.ProtoMessage.MetadataEntry
}
var file_transport_message_message_proto_depIdxs = []int32{
	1, // 0: message.ProtoMessage.metadata:type_name -> message.ProtoMessage.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transport_message_message_proto_init() }
func file_transport_message_message_proto_init() {
	if File_transport_message_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_message_message_proto_rawDesc), len(file_transport_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_message_message_proto_goTypes,
		DependencyIndexes: file_transport_message_message_proto_depIdxs,
		MessageInfos:      file_transport_message_message_proto_msgTypes,
	}.Build()
	File_transport_message_message_proto = out.File
	file_transport_message_message_proto_goTypes = nil
	file_transport_message_message_proto_depIdxs = nil
}
